---
- hosts: web
  remote_user: ubuntu
  become: yes #sudo
  # vars: #variables
  #   - dir_name: test
  #   - myname: ahmed
  #   - update: no
  vars_prompt: #variables entered in runtime
    - name: password
      prompt: please enter your password?
      private: no

  roles: #to import the web
    - web

  # tasks: 
    # - name: apt update #module1
    #   apt:
    #     upgrade: yes
    #   # when: update=="yes" #this is a condition if update = yes then update but here the value is not so it wont update
    #   when: ansible_facts["os_family"]=="Centos" and update=="yes" #checking if the facts gathered of the os are from the family debian

    # - name: install nginx #module2
    #   apt:
    #     name: nginx
    #     state: present

    # - name: create dir #module3
    #   file:
    #     path: "{{ dir_name }}"
    #     state: directory   

    # - name: #module4
    #   command: "ls {{ dir_name }}"
    #   register: results #storing the output of the previous step in a variable called results

    # - name: print stdout #module5 to print results
    #   debug:
    #     var: results.stdout #to print the output only

    # - name: copy template #module4 to copy the variavle in myconfig with the value mentioned here to the server
    #   template: #could be copy not template
    #     src: myconfig.g2 #path of the source file on my machine #if i want to copy from path to path but in the server use remote src = true instead of src
    #     dest: myconfig.g2 #path of the destination file
    #   notify: restart nginx #to link wi the handler

    # - name: create user x
    #   user: #creating users on the server with loop
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - khalid
    #     - fares
    #     - nany

  # handlers: #happens if there is a change in the linked module
  #   - name: restart nginx
  #     service:
  #       name: nginx
  #       state: restarted      

#ansible-galaxy init roleName: a command to import a ready role and ready structure and then i fill it myself